swagger: '2.0'

info:
    version: '1.0'
    title: projectFruit # Do not change it after the first deployment.

paths:
    /:
        get:
            x-cdk-lambda-handler: ./api/healthCheck.handler # Input your API function path
            description: Check API health. # Input API description
            produces:
                - application/json
            responses:
                200:
                    description: Returns the API health.
                    schema:
                        type: object
    /basket:
        get:
            x-cdk-lambda-handler: ./api/getBasket.handler
            description: Check the inside of the basket..
            produces:
                - application/json
            responses:
                200:
                    description: Show the inside of the basket.
                    schema:
                        type: object
                400:
                    description: There is no basket.
                    schema:
                        type: object
    /basket/{fruit}:
        get:
            x-cdk-lambda-handler: ./api/getBasketFruit.handler
            description: Check how many fruits are in this basket.
            produces:
                - application/json
            parameters:
                - in: path
                  name: fruit
                  required: true
                  type: string
                  description: Fruits that you want to check.
            responses:
                200:
                    description: How many fruits are in this basket.
                    schema:
                        type: object
                400:
                    description: There is no fruit in the basket.
                    schema:
                        type: object
        post:
            x-cdk-lambda-handler: ./api/postBasketFruit.handler
            description: Check how many fruits are in this basket.
            produces:
                - application/json
            parameters:
                - in: path
                  name: fruit
                  required: true
                  type: string
                  description: Fruits that you want to check.
                - in: body
                  schema:
                      type: object
                      properties:
                          count:
                              type: integer
                              required: true
            responses:
                200:
                    description: Succeeded in putting fruits in the basket.
                    schema:
                        type: object
                400:
                    description: An unknown cause error has occurred.
                    schema:
                        type: object
