swagger: "2.0"

info:
  version: "1.0"
  title: "projectCake"
  x-cdk-s3-bucket-name: "projectCakeLayers"

# basePath: /v2

paths:
  /:
    get:
      x-cdk-lambda-handler: ./example.handler # handler path
      # x-cdk-additional-library: [md5]
      description: Returns a greeting to the user!
      produces:
        - application/json
      # parameters:
      # - in: query
      #   name: test
      #   required: true
      #   type: integer
      #   description: The test
      responses:
        200:
          description: Returns the greeting.
          schema:
            type: object