swagger: "2.0"

info:
  version: "1.0"
  title: "projectCake"
  x-cdk-s3-bucket-name: "projectCakeLayers"

# basePath: /v2

paths:
  /cake:
    get:
      x-cdk-lambda-handler: ./getCake.handler # handler path
      # x-cdk-additional-library: [md5]
      description: i get existing cake. cake party!
      produces:
        - application/json
      # parameters:
      # - in: query
      #   name: test
      #   required: true
      #   type: integer
      #   description: The test
      responses:
        200:
          description: Returns the cake!
          schema:
            type: object
  /cake:
    post:
      x-cdk-lambda-handler: ./makeCake.handler # handler path
      description: i make a cake. now!
      produces:
        - application/json
      # parameters:
      # - in: query
      #   name: test
      #   required: true
      #   type: integer
      #   description: The test
      responses:
        200:
          description: make cake!
          schema:
            type: object